- name: Install list of packages
  apt: pkg={{item}} state=installed
  with_items:
       - git
       - python
       - python-pip
       - curl
       - python-dev

- debug: msg="{{ ucx_meter_location }}"

- name: Create meter path
  file: state=directory path={{ ucx_meter_location }} mode=0775

- name: pull the meter from source control
  git: repo=https://github.com/ucxchange/ucxmeter.git
        dest={{ ucx_meter_location }}
        accept_hostkey=yes
        force=yes
        version=prod

- name: ucxmeter chown
  command: /bin/chown -R ubuntu:ubuntu {{ ucx_meter_location }}

- name: ucxmeter service chmod
  file: path={{ ucx_meter_location }}/cfg/ucx-meter-service mode="u+x"

- name: runmeter chmod
  file: path={{ ucx_meter_location }}/cfg/run-meter mode="u+x"

- name: Create initial meter config
  template: src={{ item.file }}.j2 dest={{ ucx_meter_location }}/cfg/{{ ucx_meter_config_file }} mode={{ item.mode }}
  sudo: True
  with_items:
    - { file: 'conf/conf', mode: '0644' }

- name: prereq python1 - download ez-setup
  sudo: True
  command: /bin/bash -c 'curl -o /tmp/ez_setup.py https://bootstrap.pypa.io/ez_setup.py'

- name: prereq python2 - ez-setup
  sudo: True
  command: /bin/bash -c '/usr/bin/python2.7 /tmp/ez_setup.py'

- name: install libraries
  sudo: True
  command: /bin/bash -c 'pip2 install {{ item.lib }}'
  with_items:
    - { lib: 'psutil' }
    - { lib: 'netifaces' }
    - { lib: 'py-cpuinfo' }

- name: execute ucxmeter
  sudo: True
  command: /bin/bash -c '{{ ucx_meter_location }}/cfg/ucx-meter-service start'
  async: 45
  poll: 0
